apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tbr-backend-api
  name: tbr-backend-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbr-backend-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tbr-backend-api
    spec:
      automountServiceAccountToken: false
      containers:
      - image: substitute_image_name
        imagePullPolicy: IfNotPresent
        name: tbr-backend-api
        env:
        - name: LOGGING_FILE_PATH
          value: "/app/logs/"
        - name: AKV_URL
          value: substitute_akv_url
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
