apiVersion: apps/v1
kind: Deploymen
metadata:
  labels:
    app: tbr-backend-api
  name: livesports-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbr-backend-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tbr-backend-api
    spec:
      automountServiceAccountToken: false
      containers:
      - image: this_should_change
        command: ["/bin/sh",  "-c",  "envsubst < /usr/cmconfig/index.js > /app/dist/config/index.js && node /app/dist/index.js"]
        imagePullPolicy: IfNotPresent
        name: tbr-backend-api
        env:
        - name: LOGGING_FILE_PATH
          value: "/app/logs/"
        ports:
        - containerPort: 3000
          name: http
        resources:
          limit:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /usr/cmconfig
          name: tbr-backend-cm-volume
      volumes:
      - name: tbr-backend-cm-volume
        configMap:
          name: tbr-backend-config-cm
      imagePullSecrets:
      - name: tbrprodimagesecret