apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tbr-background-service
  name: tbr-background-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbr-background-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tbr-background-service
    spec:
      automountServiceAccountToken: false
      containers:
      - image: substitute_image_name
        imagePullPolicy: IfNotPresent
        name: tbr-background-service
        env:
        - name: LOGGING_FILE_PATH
          value: "/mnt/logs/"
        - name: PDF_OUTPUT_PATH
          value: "/mnt/backgroundsvc/"
        - name: AKV_URL
          value: substitute_akv_url
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: "/mnt/backgroundsvc/"
          name: azure-blob-background-invoices
        - mountPath: "/mnt/logs/"
          name: azure-blob-logs
      volumes:
      - name: azure-blob-background-invoices
        persistentVolumeClaim:
          claimName: azure-blob-background-invoices
      - name: azure-blob-logs
        persistentVolumeClaim:
          claimName: azure-blob-logs    
