# This is a basic workflow to help you get started with Actions

name: TBR Frontend Android

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      target_branch:
        description: Name of the branch for initializing build from TBR Frontend repo
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  development:
    uses: ./.github/workflows/tbr-android-reusable.yaml
    with:
      environment: Frontend_Development
      target_branch: ${{ github.event.inputs.target_branch }}
      folder: tst
    secrets: 
      GET_CODE_FROM_PRIVATE_REPO: ${{ secrets.GET_CODE_FROM_PRIVATE_REPO }}
      API_URL: ${{ secrets.API_URL }}
      GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      KEYSTORE: ${{ secrets.KEYSTORE }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_FOR_UPLOAD: ${{ secrets.AZURE_STORAGE_FOR_UPLOAD }}
      UPLOAD_APK_ACCOUNT_KEY: ${{ secrets.UPLOAD_APK_ACCOUNT_KEY }}
      
  production:
    if: github.event.inputs.target_branch == 'users/neha/r3.1'
    needs: development
    uses: ./.github/workflows/tbr-android-reusable.yaml
    with:
      environment: Frontend_Production
      target_branch: ${{ github.event.inputs.target_branch }}
      folder: prod
    secrets: 
      GET_CODE_FROM_PRIVATE_REPO: ${{ secrets.GET_CODE_FROM_PRIVATE_REPO }}
      API_URL: ${{ secrets.API_URL }}
      GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      KEYSTORE: ${{ secrets.KEYSTORE }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_FOR_UPLOAD: ${{ secrets.AZURE_STORAGE_FOR_UPLOAD }}
      UPLOAD_APK_ACCOUNT_KEY: ${{ secrets.UPLOAD_APK_ACCOUNT_KEY }}
