# This is a basic workflow to help you get started with Actions

name: TBR Node Backend Build and Deploy to K8

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          # Repository name with owner. For example, actions/checkout
          repository: The-Bike-Rentals/tbr-backend
          token: ${{ secrets.GET_CODE_FROM_PRIVATE_REPO }}
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -l
